# -*- coding: utf-8 -*-
"""Turbine_Blade_Defect_Resnet50.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LabhEhLLY6iigt_hC9AeypNsmIIZXQb6
"""

from google.colab import ai
response = ai.generate_text("What is the capital of meow?")
print(response)

import os, shutil, torch, torch.nn as nn, torch.optim as optim
from pathlib import Path
from sklearn.metrics import classification_report, confusion_matrix
from torchvision import transforms
from torch.utils.data import DataLoader, Dataset
from PIL import Image
import matplotlib.pyplot as plt
from google.colab import drive

# =========================================================
# Mount Google Drive and Setup Paths
# =========================================================
def setup_colab_paths():
    # Mount Google Drive
    drive.mount('/content/drive')

    # Path to your project folder on Drive
    PROJECT_ROOT = "/content/drive/My Drive/APS360 - Turbine Blade Project"

    # Verify the baseline_model directory exists in Drive
    src_baseline = os.path.join(PROJECT_ROOT, "baseline_model")
    if not os.path.exists(src_baseline):
        raise ValueError(f"baseline_model directory not found in Drive at {src_baseline}")

    # Verify images directory exists
    src_images = os.path.join(src_baseline, "images")
    if not os.path.exists(src_images):
        raise ValueError(f"Images directory not found at {src_images}")

    # Check if there are any image files
    image_files = [f for f in os.listdir(src_images) if f.endswith(('.png', '.jpg', '.jpeg'))]
    if not image_files:
        raise ValueError(f"No image files found in {src_images}")
    print(f"Found {len(image_files)} image files in Drive")

    # Create a local working directory (faster I/O than working directly on Drive)
    COLAB_ROOT = "/content/turbine_project"
    if os.path.exists(COLAB_ROOT):
        shutil.rmtree(COLAB_ROOT)
    os.makedirs(COLAB_ROOT, exist_ok=True)

    # Copy baseline_model folder locally
    dst_baseline = os.path.join(COLAB_ROOT, "baseline_model")
    print("Copying baseline data...")
    shutil.copytree(src_baseline, dst_baseline)

    # Verify the copy was successful
    copied_images = os.path.join(dst_baseline, "images")
    if not os.path.exists(copied_images):
        raise ValueError(f"Failed to copy images directory to {copied_images}")

    copied_files = [f for f in os.listdir(copied_images) if f.endswith(('.png', '.jpg', '.jpeg'))]
    if len(copied_files) != len(image_files):
        raise ValueError(f"Not all images were copied. Expected {len(image_files)}, got {len(copied_files)}")

    print(f"Successfully copied {len(copied_files)} images")
    return COLAB_ROOT, dst_baseline

# =========================================================
# Dataset
# =========================================================
class BladeSynthDataset(Dataset):
    def __init__(self, data_dir, split_file, transform=None):
        self.data_dir = data_dir
        self.transform = transform
        self.classes = ["Normal", "Nick", "Dent", "Scratch"]
        self.class_to_idx = {c.lower(): i for i, c in enumerate(self.classes)}

        print(f"Loading split file: {split_file}")
        self.samples = []
        missing_files = []

        with open(split_file, 'r') as f:
            for line in f:
                img_name = os.path.basename(line.strip())
                if not img_name:
                    continue

                # Add .png extension if not present
                if not os.path.splitext(img_name)[1]:
                    img_name = f"{img_name}.png"

                # Construct path relative to data_dir
                img_path = os.path.join(self.data_dir, "images", img_name)

                # Extract class from filename
                parts = os.path.splitext(img_name)[0].split('_')
                if 'valid' in parts:
                    img_class = parts[-2].lower()  # BladeSynth_valid_Dent_2133.png -> dent
                else:
                    img_class = parts[1].lower()   # BladeSynth_Dent_1126.png -> dent

                if img_class not in self.class_to_idx:
                    print(f"Warning: Unknown class '{img_class}' in {img_name}")
                    continue

                if os.path.exists(img_path):
                    self.samples.append((img_path, self.class_to_idx[img_class]))
                else:
                    missing_files.append(img_name)

        # Print class distribution
        class_counts = {}
        for _, label_idx in self.samples:
            label = self.classes[label_idx]
            class_counts[label] = class_counts.get(label, 0) + 1

        print(f"\nFound {len(self.samples)} valid images")
        print("\nClass distribution:")
        for cls, count in class_counts.items():
            print(f"{cls}: {count} images ({count/len(self.samples)*100:.1f}%)")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, label = self.samples[idx]
        image = Image.open(img_path).convert('RGB')
        if self.transform:
            image = self.transform(image)
        return image, label

def main():
    # Setup paths
    COLAB_ROOT, BASELINE_DIR = setup_colab_paths()
    IMG_DIR = os.path.join(BASELINE_DIR, 'images')
    SPLITS_DIR = os.path.join(BASELINE_DIR, 'splits')

    # Configuration
    IMG_SIZE = 224  # Increased image size for better feature extraction
    BATCH = 32      # Smaller batch size for better generalization
    EPOCHS = 50     # More epochs to ensure convergence
    LR = 3e-4      # Smaller learning rate for stability
    PATIENCE = 10   # More patience to avoid early stopping
    OUT_DIR = Path(os.path.join(BASELINE_DIR, "experiments"))
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

    print(f"Configuration:")
    print(f"- Working directory: {COLAB_ROOT}")
    print(f"- Baseline directory: {BASELINE_DIR}")
    print(f"- Output directory: {OUT_DIR}")
    print(f"- Device: {DEVICE}")

    # Data transforms
    train_tf = transforms.Compose([
        transforms.Resize((IMG_SIZE, IMG_SIZE)),
        transforms.RandomHorizontalFlip(),
        transforms.RandomVerticalFlip(),
        transforms.RandomRotation(15),
        transforms.ColorJitter(brightness=0.1, contrast=0.1),
        transforms.ToTensor(),
        transforms.Normalize([0.485,0.456,0.406], [0.229,0.224,0.225]),
    ])
    val_tf = transforms.Compose([
        transforms.Resize((IMG_SIZE, IMG_SIZE)),
        transforms.ToTensor(),
        transforms.Normalize([0.485,0.456,0.406], [0.229,0.224,0.225]),
    ])

    # Create datasets
    print("\nLoading datasets...")
    train_ds = BladeSynthDataset(BASELINE_DIR, os.path.join(SPLITS_DIR, "train.txt"), transform=train_tf)
    val_ds = BladeSynthDataset(BASELINE_DIR, os.path.join(SPLITS_DIR, "val.txt"), transform=val_tf)
    test_ds = BladeSynthDataset(BASELINE_DIR, os.path.join(SPLITS_DIR, "test.txt"), transform=val_tf)

    # Create dataloaders
    train_dl = DataLoader(train_ds, batch_size=BATCH, shuffle=True, num_workers=2)
    val_dl = DataLoader(val_ds, batch_size=BATCH, shuffle=False, num_workers=2)
    test_dl = DataLoader(test_ds, batch_size=BATCH, shuffle=False, num_workers=2)

    # Model
    class MLP(nn.Module):
        def __init__(self, in_dim, num_classes):
            super().__init__()
            self.net = nn.Sequential(
                nn.Flatten(),
                nn.Linear(in_dim, 1024), nn.ReLU(inplace=True), nn.BatchNorm1d(1024),
                nn.Dropout(0.3),
                nn.Linear(1024, 512), nn.ReLU(inplace=True), nn.BatchNorm1d(512),
                nn.Dropout(0.3),
                nn.Linear(512, 256), nn.ReLU(inplace=True), nn.BatchNorm1d(256),
                nn.Dropout(0.2),
                nn.Linear(256, num_classes)
            )

            # Initialize weights
            for m in self.modules():
                if isinstance(m, nn.Linear):
                    nn.init.kaiming_normal_(m.weight)
                    nn.init.constant_(m.bias, 0)

        def forward(self, x): return self.net(x)

    NUM_CLASSES = len(train_ds.classes)
    IN_DIM = 3*IMG_SIZE*IMG_SIZE
    model = MLP(IN_DIM, NUM_CLASSES).to(DEVICE)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=LR)

    # Training
    best_val = float("inf")
    best_path = OUT_DIR / "best_mlp.pt"
    history = {"train_loss":[], "val_loss":[], "train_acc":[], "val_acc":[]}
    no_improve = 0

    def run_epoch(dl, train_mode=True):
        model.train() if train_mode else model.eval()
        tot_loss, correct, total = 0.0, 0, 0
        with torch.set_grad_enabled(train_mode):
            for x,y in dl:
                x,y = x.to(DEVICE), y.to(DEVICE)
                if train_mode: optimizer.zero_grad()
                out = model(x)
                loss = criterion(out, y)
                if train_mode:
                    loss.backward()
                    optimizer.step()
                tot_loss += loss.item()*y.size(0)
                pred = out.argmax(1)
                correct += (pred==y).sum().item()
                total += y.size(0)
        return tot_loss/total, correct/total

    for epoch in range(1, EPOCHS+1):
        tr_loss, tr_acc = run_epoch(train_dl, True)
        va_loss, va_acc = run_epoch(val_dl, False)

        history["train_loss"].append(tr_loss)
        history["val_loss"].append(va_loss)
        history["train_acc"].append(tr_acc)
        history["val_acc"].append(va_acc)

        print(f"Epoch {epoch:02d} | train {tr_acc:.3f} loss {tr_loss:.4f} | val {va_acc:.3f} loss {va_loss:.4f}")

        if va_loss < best_val:
            best_val = va_loss
            no_improve = 0
            torch.save({
                "model": model.state_dict(),
                "classes": train_ds.classes,
                "class_to_idx": train_ds.class_to_idx,
                "img_size": IMG_SIZE
            }, best_path)
        else:
            no_improve += 1
            if no_improve >= PATIENCE:
                print("Early stopping.")
                break

    # Plot learning curves
    plt.figure(figsize=(10,4))
    plt.subplot(1,2,1)
    plt.plot(history["train_acc"], label="train")
    plt.plot(history["val_acc"], label="val")
    plt.xlabel("epoch"); plt.ylabel("accuracy")
    plt.title("MLP baseline accuracy"); plt.legend()

    plt.subplot(1,2,2)
    plt.plot(history["train_loss"], label="train")
    plt.plot(history["val_loss"], label="val")
    plt.xlabel("epoch"); plt.ylabel("loss")
    plt.title("MLP baseline loss"); plt.legend()
    plt.tight_layout()
    plt.savefig(OUT_DIR/"learning_curves.png", dpi=300)

    # Test set evaluation
    ckpt = torch.load(best_path, map_location=DEVICE)
    model.load_state_dict(ckpt["model"])
    classes = ckpt["classes"]

    y_true, y_pred = [], []
    model.eval()
    with torch.no_grad():
        for x,y in test_dl:
            x = x.to(DEVICE)
            pred = model(x).argmax(1).cpu().numpy()
            y_pred.extend(pred.tolist())
            y_true.extend(y.numpy().tolist())

    print("\nClassification report (TEST):")
    print(classification_report(y_true, y_pred, target_names=classes, digits=3))

    # Confusion matrix
    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(4,4))
    plt.imshow(cm, cmap="Blues")
    plt.xticks(range(len(classes)), classes, rotation=45, ha="right")
    plt.yticks(range(len(classes)), classes)
    for i in range(len(classes)):
        for j in range(len(classes)):
            plt.text(j, i, str(cm[i,j]), ha="center", va="center")
    plt.title("Confusion Matrix (Test)")
    plt.tight_layout()
    plt.savefig(OUT_DIR/"confusion_matrix.png", dpi=300)

    print(f"\nSaved outputs to: {OUT_DIR}")
    # Copy results back to Drive
    drive_out = Path("/content/drive/My Drive/APS360 - Turbine Blade Project/baseline_model/experiments")
    drive_out.mkdir(parents=True, exist_ok=True)
    shutil.copy2(OUT_DIR/"best_mlp.pt", drive_out/"best_mlp.pt")
    shutil.copy2(OUT_DIR/"learning_curves.png", drive_out/"learning_curves.png")
    shutil.copy2(OUT_DIR/"confusion_matrix.png", drive_out/"confusion_matrix.png")
    print(f"Copied results to Google Drive: {drive_out}")

if __name__ == "__main__":
    main()

import os, shutil, torch, torch.nn as nn, torch.optim as optim
from pathlib import Path
from sklearn.metrics import classification_report, confusion_matrix
from torchvision import transforms
from torch.utils.data import DataLoader, Dataset
from PIL import Image
import matplotlib.pyplot as plt
from google.colab import drive

# Mount Drive and Setup Paths sections remain same as your original file
def setup_colab_paths():
    # Mount Google Drive
    drive.mount('/content/drive')

    # Path to your project folder on Drive
    PROJECT_ROOT = "/content/drive/My Drive/APS360 - Turbine Blade Project"

    # Verify the baseline_model directory exists in Drive
    src_baseline = os.path.join(PROJECT_ROOT, "baseline_model")
    if not os.path.exists(src_baseline):
        raise ValueError(f"baseline_model directory not found in Drive at {src_baseline}")

    # Verify images directory exists
    src_images = os.path.join(src_baseline, "images")
    if not os.path.exists(src_images):
        raise ValueError(f"Images directory not found at {src_images}")

    # Check if there are any image files
    image_files = [f for f in os.listdir(src_images) if f.endswith(('.png', '.jpg', '.jpeg'))]
    if not image_files:
        raise ValueError(f"No image files found in {src_images}")
    print(f"Found {len(image_files)} image files in Drive")

    # Create a local working directory (faster I/O than working directly on Drive)
    COLAB_ROOT = "/content/turbine_project"
    if os.path.exists(COLAB_ROOT):
        shutil.rmtree(COLAB_ROOT)
    os.makedirs(COLAB_ROOT, exist_ok=True)

    # Copy baseline_model folder locally
    dst_baseline = os.path.join(COLAB_ROOT, "baseline_model")
    print("Copying baseline data...")
    shutil.copytree(src_baseline, dst_baseline)

    # Verify the copy was successful
    copied_images = os.path.join(dst_baseline, "images")
    if not os.path.exists(copied_images):
        raise ValueError(f"Failed to copy images directory to {copied_images}")

    copied_files = [f for f in os.listdir(copied_images) if f.endswith(('.png', '.jpg', '.jpeg'))]
    if len(copied_files) != len(image_files):
        raise ValueError(f"Not all images were copied. Expected {len(image_files)}, got {len(copied_files)}")

    print(f"Successfully copied {len(copied_files)} images")
    return COLAB_ROOT, dst_baseline

# Dataset class remains same
class BladeSynthDataset(Dataset):
    def __init__(self, data_dir, split_file, transform=None):
        self.data_dir = data_dir
        self.transform = transform
        self.classes = ["Normal", "Nick", "Dent", "Scratch"]
        self.class_to_idx = {c.lower(): i for i, c in enumerate(self.classes)}

        print(f"Loading split file: {split_file}")
        self.samples = []
        missing_files = []

        with open(split_file, 'r') as f:
            for line in f:
                img_name = os.path.basename(line.strip())
                if not img_name:
                    continue

                # Add .png extension if not present
                if not os.path.splitext(img_name)[1]:
                    img_name = f"{img_name}.png"

                # Construct path relative to data_dir
                img_path = os.path.join(self.data_dir, "images", img_name)

                # Extract class from filename
                parts = os.path.splitext(img_name)[0].split('_')
                if 'valid' in parts:
                    img_class = parts[-2].lower()  # BladeSynth_valid_Dent_2133.png -> dent
                else:
                    img_class = parts[1].lower()   # BladeSynth_Dent_1126.png -> dent

                if img_class not in self.class_to_idx:
                    print(f"Warning: Unknown class '{img_class}' in {img_name}")
                    continue

                if os.path.exists(img_path):
                    self.samples.append((img_path, self.class_to_idx[img_class]))
                else:
                    missing_files.append(img_name)

        # Print class distribution
        class_counts = {}
        for _, label_idx in self.samples:
            label = self.classes[label_idx]
            class_counts[label] = class_counts.get(label, 0) + 1

        print(f"\nFound {len(self.samples)} valid images")
        print("\nClass distribution:")
        for cls, count in class_counts.items():
            print(f"{cls}: {count} images ({count/len(self.samples)*100:.1f}%)")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, label = self.samples[idx]
        image = Image.open(img_path).convert('RGB')
        if self.transform:
            image = self.transform(image)
        return image, label

class CNN(nn.Module):
    def __init__(self, num_classes):
        super().__init__()
        # Convolutional layers
        self.features = nn.Sequential(
            # First block
            nn.Conv2d(3, 32, 3, padding=1), nn.ReLU(inplace=True),
            nn.Conv2d(32, 32, 3, padding=1), nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2),
            nn.BatchNorm2d(32),
            nn.Dropout2d(0.25),

            # Second block
            nn.Conv2d(32, 64, 3, padding=1), nn.ReLU(inplace=True),
            nn.Conv2d(64, 64, 3, padding=1), nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2),
            nn.BatchNorm2d(64),
            nn.Dropout2d(0.25),

            # Third block
            nn.Conv2d(64, 128, 3, padding=1), nn.ReLU(inplace=True),
            nn.Conv2d(128, 128, 3, padding=1), nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2),
            nn.BatchNorm2d(128),
            nn.Dropout2d(0.25),
        )

        # Calculate the size of flattened features
        with torch.no_grad():
            dummy = torch.zeros(1, 3, 224, 224)  # Using standard IMG_SIZE
            out_size = self.features(dummy).view(1, -1).size(1)

        # Fully connected layers
        self.classifier = nn.Sequential(
            nn.Linear(out_size, 512), nn.ReLU(inplace=True),
            nn.BatchNorm1d(512),
            nn.Dropout(0.5),
            nn.Linear(512, num_classes)
        )

        # Initialize weights
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight)
                if m.bias is not None:
                    nn.init.constant_(m.bias, 0)
            elif isinstance(m, nn.Linear):
                nn.init.kaiming_normal_(m.weight)
                nn.init.constant_(m.bias, 0)
            elif isinstance(m, (nn.BatchNorm2d, nn.BatchNorm1d)):
                nn.init.constant_(m.weight, 1)
                nn.init.constant_(m.bias, 0)

    def forward(self, x):
        x = self.features(x)
        x = x.view(x.size(0), -1)
        x = self.classifier(x)
        return x

def main():
    # Setup paths
    COLAB_ROOT, BASELINE_DIR = setup_colab_paths()
    IMG_DIR = os.path.join(BASELINE_DIR, 'images')
    SPLITS_DIR = os.path.join(BASELINE_DIR, 'splits')

    # Configuration
    IMG_SIZE = 224  # Standard size for CNN
    BATCH = 32
    EPOCHS = 50
    LR = 3e-4
    PATIENCE = 10
    OUT_DIR = Path(os.path.join(BASELINE_DIR, "experiments"))
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

    print(f"Configuration:")
    print(f"- Working directory: {COLAB_ROOT}")
    print(f"- Baseline directory: {BASELINE_DIR}")
    print(f"- Output directory: {OUT_DIR}")
    print(f"- Device: {DEVICE}")

    # Data transforms
    train_tf = transforms.Compose([
        transforms.Resize((IMG_SIZE, IMG_SIZE)),
        transforms.RandomHorizontalFlip(),
        transforms.RandomVerticalFlip(),
        transforms.RandomRotation(15),
        transforms.ColorJitter(brightness=0.1, contrast=0.1),
        transforms.ToTensor(),
        transforms.Normalize([0.485,0.456,0.406], [0.229,0.224,0.225]),
    ])
    val_tf = transforms.Compose([
        transforms.Resize((IMG_SIZE, IMG_SIZE)),
        transforms.ToTensor(),
        transforms.Normalize([0.485,0.456,0.406], [0.229,0.224,0.225]),
    ])

    # Create datasets and dataloaders
    print("\nLoading datasets...")
    train_ds = BladeSynthDataset(BASELINE_DIR, os.path.join(SPLITS_DIR, "train.txt"), transform=train_tf)
    val_ds = BladeSynthDataset(BASELINE_DIR, os.path.join(SPLITS_DIR, "val.txt"), transform=val_tf)
    test_ds = BladeSynthDataset(BASELINE_DIR, os.path.join(SPLITS_DIR, "test.txt"), transform=val_tf)

    train_dl = DataLoader(train_ds, batch_size=BATCH, shuffle=True, num_workers=2)
    val_dl = DataLoader(val_ds, batch_size=BATCH, shuffle=False, num_workers=2)
    test_dl = DataLoader(test_ds, batch_size=BATCH, shuffle=False, num_workers=2)

    # Create model, criterion, optimizer
    NUM_CLASSES = len(train_ds.classes)
    model = CNN(NUM_CLASSES).to(DEVICE)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=LR)

    # Training
    best_val = float("inf")
    best_path = OUT_DIR / "best_cnn.pt"  # Changed from mlp to cnn
    history = {"train_loss":[], "val_loss":[], "train_acc":[], "val_acc":[]}
    no_improve = 0

    def run_epoch(dl, train_mode=True):
        model.train() if train_mode else model.eval()
        tot_loss, correct, total = 0.0, 0, 0
        with torch.set_grad_enabled(train_mode):
            for x,y in dl:
                x,y = x.to(DEVICE), y.to(DEVICE)
                if train_mode: optimizer.zero_grad()
                out = model(x)
                loss = criterion(out, y)
                if train_mode:
                    loss.backward()
                    optimizer.step()
                tot_loss += loss.item()*y.size(0)
                pred = out.argmax(1)
                correct += (pred==y).sum().item()
                total += y.size(0)
        return tot_loss/total, correct/total

    for epoch in range(1, EPOCHS+1):
        tr_loss, tr_acc = run_epoch(train_dl, True)
        va_loss, va_acc = run_epoch(val_dl, False)

        history["train_loss"].append(tr_loss)
        history["val_loss"].append(va_loss)
        history["train_acc"].append(tr_acc)
        history["val_acc"].append(va_acc)

        print(f"Epoch {epoch:02d} | train {tr_acc:.3f} loss {tr_loss:.4f} | val {va_acc:.3f} loss {va_loss:.4f}")

        if va_loss < best_val:
            best_val = va_loss
            no_improve = 0
            torch.save({
                "model": model.state_dict(),
                "classes": train_ds.classes,
                "class_to_idx": train_ds.class_to_idx,
                "img_size": IMG_SIZE
            }, best_path)
        else:
            no_improve += 1
            if no_improve >= PATIENCE:
                print("Early stopping.")
                break

    # Plot learning curves
    plt.figure(figsize=(10,4))
    plt.subplot(1,2,1)
    plt.plot(history["train_acc"], label="train")
    plt.plot(history["val_acc"], label="val")
    plt.xlabel("epoch"); plt.ylabel("accuracy")
    plt.title("CNN accuracy"); plt.legend()

    plt.subplot(1,2,2)
    plt.plot(history["train_loss"], label="train")
    plt.plot(history["val_loss"], label="val")
    plt.xlabel("epoch"); plt.ylabel("loss")
    plt.title("CNN loss"); plt.legend()
    plt.tight_layout()
    plt.savefig(OUT_DIR/"learning_curves.png", dpi=300)

    # Test set evaluation
    ckpt = torch.load(best_path, map_location=DEVICE)
    model.load_state_dict(ckpt["model"])
    classes = ckpt["classes"]

    y_true, y_pred = [], []
    model.eval()
    with torch.no_grad():
        for x,y in test_dl:
            x = x.to(DEVICE)
            pred = model(x).argmax(1).cpu().numpy()
            y_pred.extend(pred.tolist())
            y_true.extend(y.numpy().tolist())

    print("\nClassification report (TEST):")
    print(classification_report(y_true, y_pred, target_names=classes, digits=3))

    # Confusion matrix
    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(4,4))
    plt.imshow(cm, cmap="Blues")
    plt.xticks(range(len(classes)), classes, rotation=45, ha="right")
    plt.yticks(range(len(classes)), classes)
    for i in range(len(classes)):
        for j in range(len(classes)):
            plt.text(j, i, str(cm[i,j]), ha="center", va="center")
    plt.title("Confusion Matrix (Test)")
    plt.tight_layout()
    plt.savefig(OUT_DIR/"confusion_matrix.png", dpi=300)

    print(f"\nSaved outputs to: {OUT_DIR}")
    # Copy results back to Drive
    drive_out = Path("/content/drive/My Drive/APS360 - Turbine Blade Project/baseline_model/experiments")
    drive_out.mkdir(parents=True, exist_ok=True)
    shutil.copy2(OUT_DIR/"best_cnn.pt", drive_out/"best_cnn.pt")
    shutil.copy2(OUT_DIR/"learning_curves.png", drive_out/"learning_curves_cnn.png")
    shutil.copy2(OUT_DIR/"confusion_matrix.png", drive_out/"confusion_matrix_cnn.png")
    print(f"Copied results to Google Drive: {drive_out}")

if __name__ == "__main__":
    main()

# CNN with all the data


import os, shutil, torch, torch.nn as nn, torch.optim as optim
from pathlib import Path
from sklearn.metrics import classification_report, confusion_matrix
from torchvision import transforms
from torch.utils.data import DataLoader, Dataset
from PIL import Image
import matplotlib.pyplot as plt
from google.colab import drive

# =========================================================
# Mount Google Drive and Setup Paths
# =========================================================
def setup_colab_paths():
    # Mount Google Drive
    drive.mount('/content/drive')

    # Path to your project folder on Drive
    PROJECT_ROOT = "/content/drive/My Drive/APS360 - Turbine Blade Project"

    # Verify the primary_model directory exists in Drive
    src_primary = os.path.join(PROJECT_ROOT, "primary_model")
    if not os.path.exists(src_primary):
        raise ValueError(f"primary_model directory not found in Drive at {src_primary}")

    # Verify images directory exists
    src_images = os.path.join(src_primary, "images")
    if not os.path.exists(src_images):
        raise ValueError(f"Images directory not found at {src_images}")

    # Check if there are any image files
    image_files = [f for f in os.listdir(src_images) if f.endswith(('.png', '.jpg', '.jpeg'))]
    if not image_files:
        raise ValueError(f"No image files found in {src_images}")
    print(f"Found {len(image_files)} image files in Drive")

    # Create a local working directory (faster I/O than working directly on Drive)
    COLAB_ROOT = "/content/turbine_project"
    if os.path.exists(COLAB_ROOT):
        shutil.rmtree(COLAB_ROOT)
    os.makedirs(COLAB_ROOT, exist_ok=True)

    # Copy primary_model folder locally
    dst_primary = os.path.join(COLAB_ROOT, "primary_model")
    print("Copying primary model data...")
    shutil.copytree(src_primary, dst_primary)

    # Verify the copy was successful
    copied_images = os.path.join(dst_primary, "images")
    if not os.path.exists(copied_images):
        raise ValueError(f"Failed to copy images directory to {copied_images}")

    copied_files = [f for f in os.listdir(copied_images) if f.endswith(('.png', '.jpg', '.jpeg'))]
    if len(copied_files) != len(image_files):
        raise ValueError(f"Not all images were copied. Expected {len(image_files)}, got {len(copied_files)}")

    print(f"Successfully copied {len(copied_files)} images")
    return COLAB_ROOT, dst_primary

# =========================================================
# Dataset
# =========================================================
class BladeSynthDataset(Dataset):
    def __init__(self, data_dir, split_file, transform=None):
        self.data_dir = data_dir
        self.transform = transform
        self.classes = ["Normal", "Nick", "Dent", "Scratch", "Corrosion"]
        self.class_to_idx = {c.lower(): i for i, c in enumerate(self.classes)}

        print(f"Loading split file: {split_file}")
        self.samples = []
        missing_files = []

        print(f"Reading split file from: {split_file}")
        with open(split_file, 'r') as f:
            lines = f.readlines()
            print(f"Found {len(lines)} entries in split file")

            # Debug: show first few entries from split file
            print("\nFirst few entries in split file:")
            for i, line in enumerate(lines[:2]):
                print(f"{i+1}: {line.strip()}")

            for line in lines:
                # Clean up the line and get the image name
                line = line.strip()
                if not line:
                    continue

                # First clean the line of any path prefix
                line = line.strip()
                if not line:
                    continue

                # Remove Windows path and "cleaned/images/" if present
                if "cleaned\\images\\" in line or "cleaned/images/" in line:
                    parts = line.replace('\\', '/').split('images/')
                    img_name = parts[-1]
                else:
                    img_name = os.path.basename(line)

                # Add .png extension if not present
                if not os.path.splitext(img_name)[1]:
                    img_name = f"{img_name}.png"

                # Clean up any remaining path separators
                img_name = os.path.basename(img_name)

                # Construct path relative to data_dir
                img_path = os.path.join(self.data_dir, "images", img_name)

                # Debug print for first few images
                if len(self.samples) < 2:  # Reduce debug output
                    print(f"Processing line: {line}")
                    print(f"Extracted image name: {img_name}")
                    print(f"Full path: {img_path}")
                    print(f"Exists: {os.path.exists(img_path)}\n")

                # Debug print for first few images
                if len(self.samples) < 5:
                    print(f"Processing: {img_name}")
                    print(f"Full path: {img_path}")
                    print(f"Exists: {os.path.exists(img_path)}")

                # Extract class from filename
                parts = os.path.splitext(img_name)[0].split('_')
                if 'valid' in parts:
                    img_class = parts[-2].lower()  # BladeSynth_valid_Dent_2133.png -> dent
                else:
                    img_class = parts[1].lower()   # BladeSynth_Dent_1126.png -> dent

                if img_class not in self.class_to_idx:
                    print(f"Warning: Unknown class '{img_class}' in {img_name}")
                    continue

                if os.path.exists(img_path):
                    self.samples.append((img_path, self.class_to_idx[img_class]))
                else:
                    missing_files.append(img_name)

        # Print class distribution
        class_counts = {}
        for _, label_idx in self.samples:
            label = self.classes[label_idx]
            class_counts[label] = class_counts.get(label, 0) + 1

        print(f"\nFound {len(self.samples)} valid images")
        print("\nClass distribution:")
        for cls, count in class_counts.items():
            print(f"{cls}: {count} images ({count/len(self.samples)*100:.1f}%)")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, label = self.samples[idx]
        image = Image.open(img_path).convert('RGB')
        if self.transform:
            image = self.transform(image)
        return image, label

def main():
    # Setup paths
    COLAB_ROOT, PRIMARY_DIR = setup_colab_paths()
    IMG_DIR = os.path.join(PRIMARY_DIR, 'images')
    SPLITS_DIR = os.path.join(PRIMARY_DIR, 'splits')

    # Configuration
    IMG_SIZE = 224  # Increased image size for better feature extraction
    BATCH = 32      # Smaller batch size for better generalization
    EPOCHS = 6      # Reduced to 6 epochs as requested
    LR = 3e-4      # Smaller learning rate for stability
    PATIENCE = 3    # Reduced patience since we have fewer epochs
    OUT_DIR = Path(os.path.join(PRIMARY_DIR, "experiments"))
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

    print(f"Configuration:")
    print(f"- Working directory: {COLAB_ROOT}")
    print(f"- Primary directory: {PRIMARY_DIR}")
    print(f"- Output directory: {OUT_DIR}")
    print(f"- Device: {DEVICE}")

    # Data transforms
    train_tf = transforms.Compose([
        transforms.Resize((IMG_SIZE, IMG_SIZE)),
        transforms.RandomHorizontalFlip(),
        transforms.RandomVerticalFlip(),
        transforms.RandomRotation(15),
        transforms.ColorJitter(brightness=0.1, contrast=0.1),
        transforms.ToTensor(),
        transforms.Normalize([0.485,0.456,0.406], [0.229,0.224,0.225]),
    ])
    val_tf = transforms.Compose([
        transforms.Resize((IMG_SIZE, IMG_SIZE)),
        transforms.ToTensor(),
        transforms.Normalize([0.485,0.456,0.406], [0.229,0.224,0.225]),
    ])

    # Create datasets
    print("\nLoading datasets...")
    train_split = os.path.join(SPLITS_DIR, "train.txt")
    val_split = os.path.join(SPLITS_DIR, "val.txt")
    test_split = os.path.join(SPLITS_DIR, "test.txt")

    train_ds = BladeSynthDataset(PRIMARY_DIR, train_split, transform=train_tf)
    val_ds = BladeSynthDataset(PRIMARY_DIR, val_split, transform=val_tf)
    test_ds = BladeSynthDataset(PRIMARY_DIR, test_split, transform=val_tf)

    # Create dataloaders
    train_dl = DataLoader(train_ds, batch_size=BATCH, shuffle=True, num_workers=2)
    val_dl = DataLoader(val_ds, batch_size=BATCH, shuffle=False, num_workers=2)
    test_dl = DataLoader(test_ds, batch_size=BATCH, shuffle=False, num_workers=2)

    # Model
    class MLP(nn.Module):
        def __init__(self, in_dim, num_classes):
            super().__init__()
            self.net = nn.Sequential(
                nn.Flatten(),
                nn.Linear(in_dim, 1024), nn.ReLU(inplace=True), nn.BatchNorm1d(1024),
                nn.Dropout(0.3),
                nn.Linear(1024, 512), nn.ReLU(inplace=True), nn.BatchNorm1d(512),
                nn.Dropout(0.3),
                nn.Linear(512, 256), nn.ReLU(inplace=True), nn.BatchNorm1d(256),
                nn.Dropout(0.2),
                nn.Linear(256, num_classes)
            )

            # Initialize weights
            for m in self.modules():
                if isinstance(m, nn.Linear):
                    nn.init.kaiming_normal_(m.weight)
                    nn.init.constant_(m.bias, 0)

        def forward(self, x): return self.net(x)

    NUM_CLASSES = len(train_ds.classes)
    IN_DIM = 3*IMG_SIZE*IMG_SIZE
    model = MLP(IN_DIM, NUM_CLASSES).to(DEVICE)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=LR)

    # Training
    best_val = float("inf")
    best_path = OUT_DIR / "best_mlp.pt"
    history = {"train_loss":[], "val_loss":[], "train_acc":[], "val_acc":[]}
    no_improve = 0

    def run_epoch(dl, train_mode=True):
        model.train() if train_mode else model.eval()
        tot_loss, correct, total = 0.0, 0, 0
        with torch.set_grad_enabled(train_mode):
            for x,y in dl:
                x,y = x.to(DEVICE), y.to(DEVICE)
                if train_mode: optimizer.zero_grad()
                out = model(x)
                loss = criterion(out, y)
                if train_mode:
                    loss.backward()
                    optimizer.step()
                tot_loss += loss.item()*y.size(0)
                pred = out.argmax(1)
                correct += (pred==y).sum().item()
                total += y.size(0)
        return tot_loss/total, correct/total

    for epoch in range(1, EPOCHS+1):
        tr_loss, tr_acc = run_epoch(train_dl, True)
        va_loss, va_acc = run_epoch(val_dl, False)

        history["train_loss"].append(tr_loss)
        history["val_loss"].append(va_loss)
        history["train_acc"].append(tr_acc)
        history["val_acc"].append(va_acc)

        print(f"Epoch {epoch:02d} | train {tr_acc:.3f} loss {tr_loss:.4f} | val {va_acc:.3f} loss {va_loss:.4f}")

        if va_loss < best_val:
            best_val = va_loss
            no_improve = 0
            torch.save({
                "model": model.state_dict(),
                "classes": train_ds.classes,
                "class_to_idx": train_ds.class_to_idx,
                "img_size": IMG_SIZE
            }, best_path)
        else:
            no_improve += 1
            if no_improve >= PATIENCE:
                print("Early stopping.")
                break

    # Plot learning curves
    plt.figure(figsize=(10,4))
    plt.subplot(1,2,1)
    plt.plot(history["train_acc"], label="train")
    plt.plot(history["val_acc"], label="val")
    plt.xlabel("epoch"); plt.ylabel("accuracy")
    plt.title("MLP primary accuracy"); plt.legend()

    plt.subplot(1,2,2)
    plt.plot(history["train_loss"], label="train")
    plt.plot(history["val_loss"], label="val")
    plt.xlabel("epoch"); plt.ylabel("loss")
    plt.title("MLP primary loss"); plt.legend()
    plt.tight_layout()
    plt.savefig(OUT_DIR/"learning_curves.png", dpi=300)

    # Test set evaluation
    ckpt = torch.load(best_path, map_location=DEVICE)
    model.load_state_dict(ckpt["model"])
    classes = ckpt["classes"]

    y_true, y_pred = [], []
    model.eval()
    with torch.no_grad():
        for x,y in test_dl:
            x = x.to(DEVICE)
            pred = model(x).argmax(1).cpu().numpy()
            y_pred.extend(pred.tolist())
            y_true.extend(y.numpy().tolist())

    print("\nClassification report (TEST):")
    print(classification_report(y_true, y_pred, target_names=classes, digits=3))

    # Confusion matrix
    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(4,4))
    plt.imshow(cm, cmap="Blues")
    plt.xticks(range(len(classes)), classes, rotation=45, ha="right")
    plt.yticks(range(len(classes)), classes)
    for i in range(len(classes)):
        for j in range(len(classes)):
            plt.text(j, i, str(cm[i,j]), ha="center", va="center")
    plt.title("Confusion Matrix (Test)")
    plt.tight_layout()
    plt.savefig(OUT_DIR/"confusion_matrix.png", dpi=300)

    print(f"\nSaved outputs to: {OUT_DIR}")
    # Copy results back to Drive
    drive_out = Path("/content/drive/My Drive/APS360 - Turbine Blade Project/primary_model/experiments")
    drive_out.mkdir(parents=True, exist_ok=True)
    shutil.copy2(OUT_DIR/"best_mlp.pt", drive_out/"best_mlp.pt")
    shutil.copy2(OUT_DIR/"learning_curves.png", drive_out/"learning_curves.png")
    shutil.copy2(OUT_DIR/"confusion_matrix.png", drive_out/"confusion_matrix.png")
    print(f"Copied results to Google Drive: {drive_out}")

if __name__ == "__main__":
    main()

import torch
print("cuda available:", torch.cuda.is_available())
print("device name:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else None)
print("torch built with cuda:", torch.backends.cuda.is_built())
print("torch version:", torch.__version__)

# =============================
# FINAL PRIMARY MODEL SCRIPT
# (Auto-Fixes All Split Files)
# =============================

!pip install -q albumentations==1.4.3 opencv-python

import os, shutil, json
import numpy as np
from pathlib import Path
from PIL import Image
import matplotlib.pyplot as plt
import seaborn as sns

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision.models import resnet50, ResNet50_Weights

from sklearn.metrics import classification_report, confusion_matrix

import albumentations as A
from albumentations.pytorch import ToTensorV2
from google.colab import drive


# ===========================================
# 1. MOUNT DRIVE & PATH SETUP
# ===========================================

drive.mount('/content/drive')

ROOT = "/content/drive/My Drive/APS360 - Turbine Blade Project"
PRIMARY = f"{ROOT}/primary_model"
IMG_DIR = f"{PRIMARY}/images"
SPLITS  = f"{PRIMARY}/splits"
OUT     = f"{PRIMARY}/final_experiments"

os.makedirs(OUT, exist_ok=True)

print("Using image directory:", IMG_DIR)
print("Using splits directory:", SPLITS)


# ===========================================
# 2. READ AND FIX SPLIT FILES
# ===========================================

def load_fixed_split(split_file):
    """
    Takes train.txt/val.txt/test.txt and:
    - extracts only filename
    - constructs absolute path inside primary_model/images
    - filters out missing images
    """
    fixed_paths = []

    with open(split_file, "r") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue

            fname = os.path.basename(line.replace("\\", "/"))
            full = f"{IMG_DIR}/{fname}"

            if os.path.exists(full):
                fixed_paths.append(full)

    print(f"{split_file}: {len(fixed_paths)} valid samples")
    return fixed_paths


train_list = load_fixed_split(f"{SPLITS}/train.txt")
val_list   = load_fixed_split(f"{SPLITS}/val.txt")
test_list  = load_fixed_split(f"{SPLITS}/test.txt")

if len(train_list) == 0:
    raise ValueError("❌ No images loaded — your images must be inside primary_model/images/")

CLASS_NAMES = ["Normal", "Nick", "Dent", "Scratch", "Corrosion"]
CLASS_TO_IDX = {c.lower(): i for i, c in enumerate(CLASS_NAMES)}


def get_class(fname):
    b = os.path.basename(fname).split(".")[0].split("_")
    if "valid" in b:
        cls = b[-2]
    else:
        cls = b[1] if len(b) > 1 else None
    return cls.lower() if cls else None


# ===========================================
# 3. DATASET CLASS
# ===========================================

class BladeSynth(Dataset):
    def __init__(self, file_list, transform):
        self.files = []
        self.labels = []
        self.transform = transform

        for f in file_list:
            cls = get_class(f)
            if cls in CLASS_TO_IDX:
                self.files.append(f)
                self.labels.append(CLASS_TO_IDX[cls])

        print(f"Dataset created: {len(self.files)} samples")

    def __len__(self):
        return len(self.files)

    def __getitem__(self, idx):
        path = self.files[idx]
        img = np.array(Image.open(path).convert("RGB"))
        aug = self.transform(image=img)
        return aug["image"], self.labels[idx], path


# ===========================================
# 4. TRANSFORMS
# ===========================================

IMG_SIZE = 224

train_tf = A.Compose([
    A.Resize(IMG_SIZE, IMG_SIZE),
    A.HorizontalFlip(p=0.5),
    A.VerticalFlip(p=0.3),
    A.RandomBrightnessContrast(p=0.4),
    A.Rotate(limit=20, p=0.5),
    A.Normalize(mean=(0.485, 0.456, 0.406),
                std=(0.229, 0.224, 0.225)),
    ToTensorV2(),
])

val_tf = A.Compose([
    A.Resize(IMG_SIZE, IMG_SIZE),
    A.Normalize(mean=(0.485, 0.456, 0.406),
                std=(0.229, 0.224, 0.225)),
    ToTensorV2(),
])

train_ds = BladeSynth(train_list, train_tf)
val_ds   = BladeSynth(val_list, val_tf)
test_ds  = BladeSynth(test_list, val_tf)

train_dl = DataLoader(train_ds, batch_size=32, shuffle=True, num_workers=2)
val_dl   = DataLoader(val_ds,   batch_size=32, shuffle=False, num_workers=2)
test_dl  = DataLoader(test_ds,  batch_size=32, shuffle=False, num_workers=2)


# ===========================================
# 5. MODEL SETUP
# ===========================================

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("Training on:", DEVICE)

weights = ResNet50_Weights.IMAGENET1K_V2
model = resnet50(weights=weights)
model.fc = nn.Linear(model.fc.in_features, len(CLASS_NAMES))
model = model.to(DEVICE)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-4)


# ===========================================
# 6. TRAINING LOOP
# ===========================================

def run_epoch(dl, train=True):
    model.train() if train else model.eval()
    total, correct, loss_sum = 0, 0, 0

    for imgs, labels, _ in dl:
        imgs, labels = imgs.to(DEVICE), labels.to(DEVICE)

        if train:
            optimizer.zero_grad()

        outputs = model(imgs)
        loss = criterion(outputs, labels)

        if train:
            loss.backward()
            optimizer.step()

        loss_sum += loss.item() * labels.size(0)
        correct += (outputs.argmax(1) == labels).sum().item()
        total += labels.size(0)

    return loss_sum / total, correct / total


best_val = float("inf")
best_path = f"{OUT}/best_model.pt"

EPOCHS = 10

print("\n====== TRAINING START ======\n")

for epoch in range(1, EPOCHS + 1):
    tr_loss, tr_acc = run_epoch(train_dl, True)
    va_loss, va_acc = run_epoch(val_dl, False)

    print(f"Epoch {epoch:02d}: "
          f"Train Acc={tr_acc:.3f} Loss={tr_loss:.4f} | "
          f"Val Acc={va_acc:.3f} Loss={va_loss:.4f}")

    if va_loss < best_val:
        best_val = va_loss
        torch.save(model.state_dict(), best_path)
        print("✔ Saved new best model.")

print("\nBest model saved to:", best_path)


# ===========================================
# 7. TEST SET EVALUATION
# ===========================================

model.load_state_dict(torch.load(best_path))
model.eval()

all_true, all_pred, all_paths = [], [], []

with torch.no_grad():
    for imgs, labels, paths in test_dl:
        imgs = imgs.to(DEVICE)
        outputs = model(imgs)
        preds = outputs.argmax(1).cpu().numpy()

        all_true.extend(labels.numpy().tolist())
        all_pred.extend(preds.tolist())
        all_paths.extend(paths)

print("\n===== TEST RESULTS =====")
print(classification_report(all_true, all_pred, target_names=CLASS_NAMES, digits=3))

cm = confusion_matrix(all_true, all_pred)
plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=CLASS_NAMES,
            yticklabels=CLASS_NAMES)
plt.title("Confusion Matrix")
plt.tight_layout()
plt.savefig(f"{OUT}/confusion_matrix.png")
plt.close()

print("Saved confusion matrix.")
print("\n===== DONE =====")

# ===============================================================
# REBUILD SPLITS FOR COMBINED DATASET — 70/15/15 STRATIFIED
# ===============================================================

import os, random
from pathlib import Path
from collections import defaultdict

# -------------------------
# PATHS
# -------------------------
ROOT = "/content/drive/My Drive/APS360 - Turbine Blade Project/combined_dataset"
IMG_DIR = f"{ROOT}/cleaned/images"
SPLIT_DIR = f"{ROOT}/splits"

os.makedirs(SPLIT_DIR, exist_ok=True)

print("Images folder:", IMG_DIR)
print("Splits folder:", SPLIT_DIR)

# -------------------------
# LOAD ALL FILENAMES
# -------------------------
files = sorted(os.listdir(IMG_DIR))
print("Total images detected:", len(files))

# -------------------------
# CLASS EXTRACTION FUNCTION
# -------------------------
def get_class_from_fname(fname):
    base = fname.split(".")[0]
    parts = base.split("_")
    if len(parts) < 3:
        return None
    return parts[1].lower()  # BladeSynth_<Class>_<ID>.png

# -------------------------
# GROUP FILES BY CLASS
# -------------------------
class_groups = defaultdict(list)

for fname in files:
    cls = get_class_from_fname(fname)
    if cls:
        class_groups[cls].append(fname)

print("\nClass counts:")
for cls, lst in class_groups.items():
    print(f"{cls}: {len(lst)}")

# -------------------------
# BUILD STRATIFIED SPLITS
# -------------------------
train_list = []
val_list = []
test_list = []

for cls, lst in class_groups.items():
    random.shuffle(lst)
    n = len(lst)

    n_train = int(n * 0.70)
    n_val   = int(n * 0.15)
    n_test  = n - n_train - n_val

    train_list += [f"{IMG_DIR}/{x}" for x in lst[:n_train]]
    val_list   += [f"{IMG_DIR}/{x}" for x in lst[n_train:n_train+n_val]]
    test_list  += [f"{IMG_DIR}/{x}" for x in lst[n_train+n_val:]]

print("\nFinal split sizes:")
print("Train:", len(train_list))
print("Val:", len(val_list))
print("Test:", len(test_list))

# -------------------------
# SAVE SPLIT FILES
# -------------------------
def save_list(path, lst):
    with open(path, "w") as f:
        for item in lst:
            f.write(item + "\n")

save_list(f"{SPLIT_DIR}/train.txt", train_list)
save_list(f"{SPLIT_DIR}/val.txt", val_list)
save_list(f"{SPLIT_DIR}/test.txt", test_list)

print("\n✔ Splits successfully rebuilt!")
print("train.txt, val.txt, test.txt saved to:", SPLIT_DIR)

# ============================================================
# APS360 FINAL PROJECT — ONE-CLICK FIGURE GENERATOR
# Uses pre-trained model + combined_dataset
# ============================================================

print("===== INITIALIZING FINAL FIGURE GENERATION =====")

import os, random, numpy as np
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision.models import resnet50
import albumentations as A
from albumentations.pytorch import ToTensorV2
from sklearn.metrics import confusion_matrix, classification_report

from google.colab import drive
drive.mount('/content/drive')


# ------------------------------------------------------------
# PATH SETUP
# ------------------------------------------------------------
ROOT = "/content/drive/My Drive/APS360 - Turbine Blade Project"
DATA_DIR = f"{ROOT}/combined_dataset/cleaned/images"
SPLITS_DIR = f"{ROOT}/combined_dataset/splits"
MODEL_PATH = f"{ROOT}/primary_model/final_experiments/best_model.pt"

OUTPUT_DIR = "final_figures"
os.makedirs(OUTPUT_DIR, exist_ok=True)


# ------------------------------------------------------------
# FIX SPLITS — KEEP ONLY FILENAMES THAT ACTUALLY EXIST
# ------------------------------------------------------------
print("Fixing split files...")

all_images = set(os.listdir(DATA_DIR))

def fix_split_file(path):
    valid = []
    with open(path, "r") as f:
        for line in f:
            fname = os.path.basename(line.strip())
            if fname in all_images:
                valid.append(f"{DATA_DIR}/{fname}")

    # Rewrite cleaned split with filenames only
    with open(path, "w") as f:
        for p in valid:
            f.write(os.path.basename(p) + "\n")

    print(f"{path}: {len(valid)} valid images")
    return valid


train_list = fix_split_file(f"{SPLITS_DIR}/train.txt")
val_list   = fix_split_file(f"{SPLITS_DIR}/val.txt")
test_list  = fix_split_file(f"{SPLITS_DIR}/test.txt")

if len(train_list) == 0:
    raise ValueError("❌ No images found — check combined_dataset structure.")


# ------------------------------------------------------------
# DATASET CLASS
# ------------------------------------------------------------
CLASS_NAMES = ["Normal", "Nick", "Dent", "Scratch", "Corrosion"]
CLASS_TO_IDX = {c.lower(): i for i, c in enumerate(CLASS_NAMES)}

def parse_class(fname):
    parts = fname.split("_")
    if "valid" in parts:
        return parts[-2].lower()
    return parts[1].lower()

val_tf = A.Compose([
    A.Resize(224,224),
    A.Normalize(mean=(0.485,0.456,0.406), std=(0.229,0.224,0.225)),
    ToTensorV2(),
])

class BladeSynth(Dataset):
    def __init__(self, file_list):
        self.files, self.labels = [], []
        for f in file_list:
            cls = parse_class(os.path.basename(f))
            if cls in CLASS_TO_IDX:
                self.files.append(f)
                self.labels.append(CLASS_TO_IDX[cls])

    def __len__(self): return len(self.files)

    def __getitem__(self, idx):
        p = self.files[idx]
        img = np.array(Image.open(p).convert("RGB"))
        img_t = val_tf(image=img)["image"]
        return img_t, self.labels[idx], p


test_ds = BladeSynth(test_list)
test_dl = DataLoader(test_ds, batch_size=32, shuffle=False)

print(f"Final dataset sizes — Train={len(train_list)}, Val={len(val_list)}, Test={len(test_list)}")


# ------------------------------------------------------------
# LOAD MODEL (NO TRAINING)
# ------------------------------------------------------------
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", DEVICE)

model = resnet50(weights=None)
model.fc = nn.Linear(model.fc.in_features, len(CLASS_NAMES))
model.load_state_dict(torch.load(MODEL_PATH, map_location=DEVICE))
model = model.to(DEVICE)
model.eval()


# ------------------------------------------------------------
# INFERENCE ON TEST SET
# ------------------------------------------------------------
print("Running inference...")

all_true, all_pred = [], []

with torch.no_grad():
    for imgs, labels, paths in test_dl:
        preds = model(imgs.to(DEVICE)).argmax(1).cpu().numpy()
        all_true.extend(labels.numpy().tolist())
        all_pred.extend(preds.tolist())

print("\n=== Classification Report ===")
print(classification_report(all_true, all_pred, target_names=CLASS_NAMES))


# ------------------------------------------------------------
# FIGURE 1: SAMPLE IMAGE
# ------------------------------------------------------------
print("→ sample_image.png")
sample_filename = random.choice(os.listdir(DATA_DIR))
sample_path = f"{DATA_DIR}/{sample_filename}"
img = Image.open(sample_path)

plt.imshow(img)
plt.axis("off")
plt.savefig(f"{OUTPUT_DIR}/sample_image.png", dpi=300)
plt.close()


# ------------------------------------------------------------
# FIGURE 2: CONFUSION MATRIX
# ------------------------------------------------------------
print("→ confusion_matrix.png")

cm = confusion_matrix(all_true, all_pred)
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES)
plt.title("Confusion Matrix")
plt.savefig(f"{OUTPUT_DIR}/confusion_matrix.png", dpi=300)
plt.close()


# ------------------------------------------------------------
# FIGURE 3: SAMPLE PREDICTIONS (6 images)
# ------------------------------------------------------------
print("→ sample_predictions.png")

indices = random.sample(range(len(test_ds)), 6)
plt.figure(figsize=(12,8))

for i, idx in enumerate(indices):
    img_t, label, path = test_ds[idx]
    pred = model(img_t.unsqueeze(0).to(DEVICE)).argmax(1).item()

    vis = img_t.permute(1,2,0).cpu().numpy()

    plt.subplot(2,3,i+1)
    plt.imshow(vis)
    plt.title(f"T:{CLASS_NAMES[label]} | P:{CLASS_NAMES[pred]}")
    plt.axis("off")

plt.savefig(f"{OUTPUT_DIR}/sample_predictions.png", dpi=300)
plt.close()


# ------------------------------------------------------------
# FIGURE 4: GRAD-CAM (fixed API, 4 images)
# ------------------------------------------------------------
print("→ Grad-CAM images ...")
!pip install -q grad-cam

from pytorch_grad_cam import GradCAM
from pytorch_grad_cam.utils.image import show_cam_on_image

target_layers = [model.layer4[-1]]
cam = GradCAM(model=model, target_layers=target_layers)

for i in range(4):
    img_t, label, path = test_ds[random.randint(0, len(test_ds)-1)]
    inp = img_t.unsqueeze(0).to(DEVICE)

    rgb = img_t.permute(1,2,0).cpu().numpy()
    rgb_norm = (rgb - rgb.min()) / (rgb.max() - rgb.min() + 1e-8)

    grayscale = cam(input_tensor=inp)[0]
    cam_img = show_cam_on_image(rgb_norm, grayscale, use_rgb=True)

    plt.imshow(cam_img)
    plt.axis("off")
    plt.savefig(f"{OUTPUT_DIR}/gradcam_{i}.png", dpi=300)
    plt.close()

print("===== ALL FIGURES SAVED IN final_figures/ =====")

# ================================================
# GENERATE LEARNING CURVES FROM TRAINING LOG
# ================================================

import matplotlib.pyplot as plt
import os

os.makedirs("final_figures", exist_ok=True)

# ------------------------------------------------
# RECONSTRUCT HISTORY FROM LOG YOU PROVIDED
# ------------------------------------------------
history = {
    "train_acc":  [0.888, 0.984, 0.987, 0.989, 0.991, 0.990, 0.993, 0.992, 0.990, 0.992],
    "train_loss": [0.3118, 0.0574, 0.0469, 0.0384, 0.0315, 0.0342, 0.0237, 0.0266, 0.0298, 0.0316],
    "val_acc":    [0.986, 0.991, 0.993, 0.995, 0.996, 0.995, 0.994, 0.994, 0.997, 0.995],
    "val_loss":   [0.0600, 0.0339, 0.0232, 0.0175, 0.0153, 0.0162, 0.0226, 0.0187, 0.0122, 0.0158]
}

epochs = range(1, 11)

# ------------------------------------------------
# PLOT LEARNING CURVES
# ------------------------------------------------
plt.figure(figsize=(10,4))

# Loss subplot
plt.subplot(1,2,1)
plt.plot(epochs, history["train_loss"], label="Train Loss", marker="o")
plt.plot(epochs, history["val_loss"], label="Val Loss", marker="o")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Loss Curve")
plt.grid(True, linestyle="--", alpha=0.5)
plt.legend()

# Accuracy subplot
plt.subplot(1,2,2)
plt.plot(epochs, history["train_acc"], label="Train Acc", marker="o")
plt.plot(epochs, history["val_acc"], label="Val Acc", marker="o")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("Accuracy Curve")
plt.grid(True, linestyle="--", alpha=0.5)
plt.legend()

plt.tight_layout()
plt.savefig("final_figures/learning_curves.png", dpi=300)
plt.show()

print("Saved: final_figures/learning_curves.png")

# =====================================================
# 0. Imports
# =====================================================
import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image
from sklearn.metrics import confusion_matrix

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision.models import resnet50
import albumentations as A
from albumentations.pytorch import ToTensorV2

from google.colab import drive
drive.mount('/content/drive')

# =====================================================
# 1. Paths
# =====================================================
ROOT = "/content/drive/My Drive/APS360 - Turbine Blade Project"
IMG_DIR = f"{ROOT}/primary_model/images"
SPLITS = f"{ROOT}/primary_model/splits"
MODEL_PATH = f"{ROOT}/primary_model/final_experiments/best_model.pt"

CLASS_NAMES = ["Normal", "Nick", "Dent", "Scratch", "Corrosion"]
CLASS_TO_IDX = {c.lower(): i for i, c in enumerate(CLASS_NAMES)}

# =====================================================
# 2. Read test split
# =====================================================
test_files = []
with open(f"{SPLITS}/test.txt", "r") as f:
    for line in f:
        fname = line.strip()
        full = f"{IMG_DIR}/{fname}"
        if os.path.exists(full):
            test_files.append(full)

print("Loaded test samples:", len(test_files))

# =====================================================
# 3. Dataset
# =====================================================
val_tf = A.Compose([
    A.Resize(224,224),
    A.Normalize(mean=(0.485,0.456,0.406),
                std=(0.229,0.224,0.225)),
    ToTensorV2(),
])

def extract_class(fname):
    parts = os.path.basename(fname).split("_")
    return parts[1].lower()

class BladeSynth(Dataset):
    def __init__(self, files):
        self.files, self.labels = [], []
        for f in files:
            cls = extract_class(f)
            if cls in CLASS_TO_IDX:
                self.files.append(f)
                self.labels.append(CLASS_TO_IDX[cls])

    def __len__(self): return len(self.files)

    def __getitem__(self, idx):
        path = self.files[idx]
        img = np.array(Image.open(path).convert("RGB"))
        img_t = val_tf(image=img)["image"]
        return img_t, self.labels[idx], path

test_ds = BladeSynth(test_files)
test_dl = DataLoader(test_ds, batch_size=32, shuffle=False)

# =====================================================
# 4. Load model
# =====================================================
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", DEVICE)

model = resnet50(weights=None)
model.fc = nn.Linear(model.fc.in_features, len(CLASS_NAMES))
model.load_state_dict(torch.load(MODEL_PATH, map_location=DEVICE))
model = model.to(DEVICE)
model.eval()

# =====================================================
# 5. Run inference → get all_true, all_pred
# =====================================================
all_true, all_pred = [], []

with torch.no_grad():
    for imgs, labels, _ in test_dl:
        preds = model(imgs.to(DEVICE)).argmax(1).cpu().numpy()
        all_true.extend(labels.numpy())
        all_pred.extend(preds)

# =====================================================
# 6. Compute per-class accuracy & plot
# =====================================================
cm = confusion_matrix(all_true, all_pred)
per_class_acc = cm.diagonal() / cm.sum(axis=1)

os.makedirs("final_figures", exist_ok=True)

plt.figure(figsize=(8,5))
bars = plt.bar(CLASS_NAMES, per_class_acc, color="steelblue")

for bar, acc in zip(bars, per_class_acc):
    plt.text(bar.get_x() + bar.get_width()/2, acc + 0.02,
             f"{acc*100:.1f}%", ha="center", fontsize=12)

plt.ylim(0, 1.15)
plt.ylabel("Accuracy")
plt.title("Test Accuracy Per Class (Unseen Data)")
plt.grid(axis="y", linestyle="--", alpha=0.4)

plt.tight_layout()
plt.savefig("final_figures/test_accuracy.png", dpi=300)
plt.show()

print("Saved: final_figures/test_accuracy.png")